//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dmdbEntities : DbContext
    {
        public dmdbEntities()
            : base("name=dmdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<idea_approved> idea_approved { get; set; }
        public virtual DbSet<idea_entry> idea_entry { get; set; }
        public virtual DbSet<tags_master> tags_master { get; set; }
        public virtual DbSet<user_entry> user_entry { get; set; }
        public virtual DbSet<user_log> user_log { get; set; }
    }
}
