//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_entry
    {
        public int id { get; set; }
        public string comp_name { get; set; }
        public string ctags { get; set; }
        public string caddress { get; set; }
        public string cemail { get; set; }
        public string caltemail { get; set; }
        public string cmobile { get; set; }
        public string caltmobile { get; set; }
        public string addnotes { get; set; }
    }
}
